import img from "@/app/public/images/bandicam2024-10-0407-46-31-391-ezgif.com-video-to-gif-converter.gif"
import Image from "next/image"
import projects from "@/data/projects.json"
import { Container } from "../components/container"
import { Heading } from "../components/heading"
import { ProjectsComponent } from "../components/projects"
import  {Project}  from "@/types/project"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Ahmed`s projects",
    description: "Generated by Ahmed Khaled",
  };
const ProjectsPage = ()=>{

    const ProjectsData:Project[]= projects
    return (
        <Container>
           <div className="mb-4">

            <Heading title="My Projects" 
            text="Projects made with Love and Passion" 
            text1="100 % Responsive"
            text2="100 % User friendly"
            >
            </Heading>
            
            </div>
            {
    ProjectsData.map((project)=>

        <ProjectsComponent project ={project}>

        </ProjectsComponent>
        
    )
}
        </Container>
    )
}
export default ProjectsPage